Table "customer" {
  "id" INT(11) [pk, not null]
  "phone" VARCHAR(50) [default: NULL]
  "event" INT(11) [not null, note: 'time created in CRM']
  "fullname" VARCHAR(50) [not null]
  "nickname" VARCHAR(50) [default: NULL]
  "email" VARCHAR(255) [default: NULL]
  "mobile" VARCHAR(50) [default: NULL]
  "mobile2" VARCHAR(200) [default: NULL]
  "bbm" VARCHAR(20) [default: NULL]
  "address" TEXT [default: NULL]
  "city" VARCHAR(50) [default: NULL]
  "country" VARCHAR(50) [default: NULL]
  "profession" VARCHAR(50) [default: NULL]
  "birthday" DATE [default: NULL]
  "religion" VARCHAR(20) [default: NULL]
  "info" TEXT [default: NULL]
  "trading" TEXT [default: NULL]
  "marketing" VARCHAR(10) [default: NULL]
  "maintenance" VARCHAR(10) [default: NULL]
  "investor" TINYINT(4) [not null, default: "0", note: '0:none, 1:closed, 2:declined, 3:invalid']
  "source" VARCHAR(20) [default: NULL, note: 'brokers (0:manual)']
  "prospect" TINYINT(4) [default: NULL, note: '1: alot, 2: hot']
  "take_over" TINYINT(4) [default: "0"]
  "rolling" BIGINT(20) [default: NULL, note: 'save unixtime when opportunity is assigned/rolling']
  "expired" BIGINT(20) [default: NULL, note: 'save unixtime for expired data']
  "merge_id" INT(11) [default: NULL]
  "noteadm" TEXT [default: NULL]
  "notemkt" TEXT [default: NULL]
  "pin" TINYINT(4) [default: NULL, note: 'pin priority client']
  "MODIFY_TIME" BIGINT(20) [not null]

Indexes {
  (email, phone, source, merge_id) [unique, name: "unik_customer"]
  marketing [name: "idx_marketing"]
  fullname [name: "fullname"]
  phone [name: "phone"]
  mobile [name: "mobile"]
  maintenance [name: "maintenance"]
  rolling [name: "rolling"]
  expired [name: "expired"]
  prospect [name: "prospect"]
  source [name: "source"]
  pin [name: "pin"]
  mobile2 [name: "mobile2"]
  take_over [name: "customer_take_over"]
}
}
