Table "srcims" {
  "id" INT(11) [pk, not null, increment]
  "crm_id" INT(11) [default: NULL]
  "registered" INT(11) [not null]
  "ims_id" VARCHAR(20) [not null]
  "username" VARCHAR(50) [default: NULL]
  "fullname" VARCHAR(50) [not null]
  "email" VARCHAR(50) [not null]
  "phone" VARCHAR(30) [not null]
  "mobile" VARCHAR(30) [default: NULL]
  "bbm" VARCHAR(20) [default: NULL]
  "birthday" DATE [default: NULL]
  "source" INT(11) [not null]
  "address" TEXT [default: NULL]
  "city" VARCHAR(50) [default: NULL]
  "country" VARCHAR(50) [not null]
  "first_ref" TEXT [default: NULL, note: 'user_ref_url (MRG)']
  "last_ref" TEXT [default: NULL]
  "first_visit" TEXT [default: NULL]
  "goal_ref" TEXT [default: NULL]
  "referrer" VARCHAR(50) [default: NULL]
  "bankname" VARCHAR(20) [default: NULL]
  "bankaccno" VARCHAR(20) [default: NULL]
  "bankreg" VARCHAR(100) [default: NULL]
  "info_regis" TINYINT(4) [not null, default: "1", note: '1: new regis , 2: regis ulang ,  3: international']
  "investor" TINYINT(4) [default: NULL, note: '1: investor']
  "email_ver" TINYINT(4) [not null, default: "0"]
  "notes" TEXT [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  (ims_id, email, source, username) [unique, name: "UNIK"]
  fullname [name: "fullname"]
  email [name: "email"]
  phone [name: "phone"]
  username [name: "username"]
  crm_id [name: "crm_id"]
  source [name: "source"]
}
}
